spring.application.name=employee-task-attendance-system

spring.datasource.url=jdbc:mysql://localhost:3306/zaindb?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=zain@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

